#!/bin/bash

# Visar alla djur som har ett a
# grep a djurfil

# -E rekommenderas då den gör uttrycken lättare att läsa
# grep -E 'ens$' djurfil

# Exempel1: med å också innan
grep -E 'å.*ens$' djurfil

# Bra sida: regex101.com
