#!/bin/bash

a="hund"

read -r -p "Vilket husdjur har du hemma? " b

if [ "$a" = "$b" ]; then
    echo "A $a är samma sak som B $b"
elif [ "$b" = "giraff" ]; then
    echo "Knappast!"
elif [ "$b" = "rådjur" ]; then
    echo "Äter ibland animaliskt."
elif [ "$b" = "snok" -o "$b" = "katt" ]; then
    echo "Fint med $b."
elif [ "$b" = "hamster" ] || [ "$b" = "nakenråtta" ]; then
    echo "Fult med $b."
else
    echo "$b är nog ett bra djur!"
fi

echo "Nog om djur..."
