#!/bin/bash

a="hund"

read -r -p "Vilket husdjur har du hemma? " b

if [ "$a" = "$b" ]; then
    echo "A $a är samma sak som B $b"
elif [ "$b" = "giraff" ]; then
    echo "Knappast!"
elif [ "$b" = "rådjur" ]; then
    echo "Äter ibland animaliskt."
else
    echo "$b är nog ett bra djur!"
fi

echo "Nog om djur..."
