FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt install -y python3
RUN apt install -y python3-pip
RUN pip3 install Flask --break-system-packages

WORKDIR /app
# punkten betyder nu /app
COPY app.py .

CMD ["flask", "--app", "/app/app.py", "--host", "0.0.0.0", "run"]
